### ISSUE TITLE
最大画像サイズ、保存ファイル数

### ISSUE THREAD

**Issue by rafale2k** [aphmaunejitsu/uproda#13]
決めるのは一通りできてからで
最後にyamlに書けばおしまいだと思うけど
頭出しという意味で。

個人的思いとしては5MBまで、ファイル数は500くらいかなぁ
なんて想定してる。

**Comment by aphmaunejitsu** [comment]
今は、2mbの5000ファイルにしている
後からいくらでも変えられるので、今は何でもいいかなーって思ってる

**Comment by rafale2k** [comment]
極端な話、運用後でもさっくり変えられるもんね
ファイル数はサムネ含めてパフォーマンスに影響しそうで増やすの怖いのと
単発のサイズは最近大きくなる一方なので
悩むなぁと

**Comment by aphmaunejitsu** [comment]
ファイル数は、物理的なパフォーマンスに、あんまり影響出ないようにしたつもり
Mysqlのパフォーマンスが足を引っ張る可能性あるけど、まあこの程度なら・・・
一応、Mysql周りは最悪マスタースレーブ構成にスケールアウトしやすいように作ってあるけど
必要ないかと思われるー

メモキャッシュとかRedisとかカウチベースとかで頑張りたけいけど、いくらの鯖になんねんと！
そんなことやり始めたら、割とimgur的なの作れちゃうよ・・・

**Comment by rafale2k** [comment]
memcached使いたい！
→そうだ石狩のVPSだ！
→みんなはさーん

**Comment by new2ch** [comment]
DBがあるのであれば総容量で古いものから削除できる気がする

**Comment by rafale2k** [comment]
これもPendingでいいかも

**Comment by aphmaunejitsu** [comment]
移動したっ

**Comment by rafale2k** [comment]
ありあぽー

**Comment by rafale2k** [comment]
取り敢えずは5Mの2000ファイルで
ファイル数多すぎな気もするけど前はどうだったんだろうね？

**Comment by rafale2k** [comment]
10Mの1000ファイルでいいのでは説も出てる

**Comment by aphmaunejitsu** [comment]
そうしちゃってもいいかもねー。
というか、https-portalからの通信のせいで、全IPが同じIPになってるぅ

**Comment by rafale2k** [comment]
それ投稿元でアレするのに影響ない？

webm対応のタイミングで10Mまでにしよう

**Comment by aphmaunejitsu** [comment]
影響あるんよ(ﾉ∀`)
なので、ちょっと調査中

**Comment by rafale2k** [comment]
XーFORWADED－FORとか付いてないんかな

**Comment by aphmaunejitsu** [comment]
対応できた( ´∀｀)
直で書き換えたw
あとで、gitにコミットしとくw

**Comment by rafale2k** [comment]
おつおつ
バンバン本番書き換えようじぇｗ

**Comment by rafale2k** [comment]
取り敢えず鯖容量は余裕あるけど、一旦クローズで！
