### ISSUE TITLE
アップロードのキャプチャ対応

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#16]
荒らし対策その１
頑張るお

https://github.com/ha1t/php-Auth_Kitten

**Comment by aphmaunejitsu** [comment]
真面目に作り出したら、一個reCaptchaアプリができちゃうっていう
googleのrecaptchaで逃げつつ、オススメキャプチャ作ることにしよう・・・

**Comment by rafale2k** [comment]
Googleのでいいと思いますお
そこまで頑張る部分でもないだろうし

**Comment by aphmaunejitsu** [comment]
そだねー。
でもオススメキャプチャはちょっと作りたいw

**Comment by rafale2k** [comment]
気持ちは大いにわかるので、負担にならない程度であればｗ

**Comment by aphmaunejitsu** [comment]
余裕があればやるお！(ﾟ∀ﾟ)

**Comment by aphmaunejitsu** [comment]
シンプルなやつで、一旦逃げ・・・

**Comment by rafale2k** [comment]
Notice
======

This project is no longer maintained.

てのがちょと怖いね

**Comment by aphmaunejitsu** [comment]
確かに・・・一番上を読んでなかったw

**Comment by aphmaunejitsu** [comment]
一旦、整理のためにクローズ
