### ISSUE TITLE
TOR出口対策

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#17]
荒らし対策その２

**Comment by rafale2k** [comment]
これってどこかからリスト定期的に引っ張ってきて
DBに突っ込むのがいいのかしら？

**Comment by aphmaunejitsu** [comment]
１日一回引っ張ってきて、DBに突っ込む予定どすー
キャプチャ入れたら不要かもしれないけど、TORの投稿を防げるかなっと。

**Comment by new2ch** [comment]
https://www.dan.me.uk/dnsbl

**Comment by rafale2k** [comment]
DNSBLは2chでも使ってるけど、個人的にはあてにしたくない

**Comment by aphmaunejitsu** [comment]
一応でけた
