### ISSUE TITLE
NGワード対応

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#26]
NGワードの対応

**Comment by rafale2k** [comment]
クローズしたところｱﾚだけど、14とかも入れたいｗ

**Comment by aphmaunejitsu** [comment]
yamlで個別に追加できるのでっ

**Comment by aphmaunejitsu** [comment]
yamlはダメだったんだった
設定ファイルでやったんだった。
https://github.com/aphmaunejitsu/uproda/blob/develop/fuel/app/config/spamwords.php

**Comment by rafale2k** [comment]
大量に入ってるなぁと思いながら、ジューシーポークとか
ネ実ポイのも必要かな？とかDTV関係も、とか
まぁ全然急ぐ内容じゃないねｗ
