### ISSUE TITLE
拒否IPの対応

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#27]
拒否IPの対応

**Comment by aphmaunejitsu** [comment]
これは基本出口ノード拒否用
個別に追加もあり

**Comment by rafale2k** [comment]
002_alter_table_deny_upload のupとdownで列の並びが違うのが気になったマン
DNSBLは使いたくないけど、どこかから定期的に引っ張ってきて更新は
必要だろうねぇ。
個人的にはac.jpの荒らしは多いので(★経験から)これらも弾きたい

**Comment by aphmaunejitsu** [comment]
なるほど！
その辺の固定のやつは、NGワードみたいに設定ファイルで弾きますかー

**Comment by rafale2k** [comment]
設定ファイルにしちゃう？
別テーブルで突っ込むのもありかなとも思ってた
