### ISSUE TITLE
faviconが・・・

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#30]
fuelphp標準、誰か作って欲しいお（＾ω＾ ≡ ＾ω＾）

**Comment by B-CAS** [comment]
他板荒らした挙句無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？>>1
>>2ンゴンゴンゴｗｗｗｗｗｗｗｗｗｗ>>3ｗｗｗｗ(岩嵜) ンゴーンゴーｗｗｗｗｗｗｗｗｗｗｗｗ
(>>3o)ﾉンーゴンゴン>>2>>3んJ>>9o｡ンゴンゴッ(岩嵜)ンゴンゴンゴンゴッ ヽ(岩嵜)ﾉなんＪ
い>>4んのか(すまんな) (`o)ヨダヨダヨダヨダ肩幅 (`o)ありがとうどういたしましてを忘れてる(`o)今の時代に終止符だ(何をそんなに) ｡･ﾟ･(`o)･ﾟ･｡
ゆくんだなんＪ(いかんの>>3 (`o)勝負だなんＪ(いかんでしょ) o(`o)o勝利を掴め(おＪか)
(無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？
ちょｗｗｗｗなんｊにもVIPPERがｗｗｗｗよなんｊ民ゥーｗｗｗｗｗｗ

**Comment by rafale2k** [comment]
これは稼働したら即いいの作る人が出そうｗ

**Comment by aphmaunejitsu** [comment]
そうだと嬉しいっ

**Comment by rafale2k** [comment]
素晴らしいのをいただいたのでこれは終わりでいいかも
