### ISSUE TITLE
シンプル画像一覧

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#31]
#22 でトップをサムネイル一覧とシンプルな一覧に入れ替える

**Comment by B-CAS** [comment]
他板荒らした挙句無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？>>1
>>2ンゴンゴンゴｗｗｗｗｗｗｗｗｗｗ>>3ｗｗｗｗ(岩嵜) ンゴーンゴーｗｗｗｗｗｗｗｗｗｗｗｗ
(>>3o)ﾉンーゴンゴン>>2>>3んJ>>9o｡ンゴンゴッ(岩嵜)ンゴンゴンゴンゴッ ヽ(岩嵜)ﾉなんＪ
い>>4んのか(すまんな) (`o)ヨダヨダヨダヨダ肩幅 (`o)ありがとうどういたしましてを忘れてる(`o)今の時代に終止符だ(何をそんなに) ｡･ﾟ･(`o)･ﾟ･｡
ゆくんだなんＪ(いかんの>>3 (`o)勝負だなんＪ(いかんでしょ) o(`o)o勝利を掴め(おＪか)
(無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？
ちょｗｗｗｗなんｊにもVIPPERがｗｗｗｗよなんｊ民ゥーｗｗｗｗｗｗ

**Comment by B-CAS** [comment]
他板荒らした挙句無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？>>1
>>2ンゴンゴンゴｗｗｗｗｗｗｗｗｗｗ>>3ｗｗｗｗ(岩嵜) ンゴーンゴーｗｗｗｗｗｗｗｗｗｗｗｗ
(>>3o)ﾉンーゴンゴン>>2>>3んJ>>9o｡ンゴンゴッ(岩嵜)ンゴンゴンゴンゴッ ヽ(岩嵜)ﾉなんＪ
い>>4んのか(すまんな) (`o)ヨダヨダヨダヨダ肩幅 (`o)ありがとうどういたしましてを忘れてる(`o)今の時代に終止符だ(何をそんなに) ｡･ﾟ･(`o)･ﾟ･｡
ゆくんだなんＪ(いかんの>>3 (`o)勝負だなんＪ(いかんでしょ) o(`o)o勝利を掴め(おＪか)
(無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？
ちょｗｗｗｗなんｊにもVIPPERがｗｗｗｗよなんｊ民ゥーｗｗｗｗｗｗ

**Comment by B-CAS** [comment]
他板荒らした挙句無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？>>1
>>2ンゴンゴンゴｗｗｗｗｗｗｗｗｗｗ>>3ｗｗｗｗ(岩嵜) ンゴーンゴーｗｗｗｗｗｗｗｗｗｗｗｗ
(>>3o)ﾉンーゴンゴン>>2>>3んJ>>9o｡ンゴンゴッ(岩嵜)ンゴンゴンゴンゴッ ヽ(岩嵜)ﾉなんＪ
い>>4んのか(すまんな) (`o)ヨダヨダヨダヨダ肩幅 (`o)ありがとうどういたしましてを忘れてる(`o)今の時代に終止符だ(何をそんなに) ｡･ﾟ･(`o)･ﾟ･｡
ゆくんだなんＪ(いかんの>>3 (`o)勝負だなんＪ(いかんでしょ) o(`o)o勝利を掴め(おＪか)
(無関係のTwitterアカウントいじめてはずかしくないのかな糞ネ実民？
ちょｗｗｗｗなんｊにもVIPPERがｗｗｗｗよなんｊ民ゥーｗｗｗｗｗｗ

**Comment by aphmaunejitsu** [comment]
スマホだと、サムネイル表示の方が、縦スクロールが少なくて済むなあ・・・

**Comment by aphmaunejitsu** [comment]
リスト表示の項目を、もうちょっと考えるー。
