### ISSUE TITLE
管理サイト

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#44]
- ユースケース
  - 画像を削除する
  - 拒否IPを追加する
  - 拒否ワードを追加する

このくらいかな
ログインとか当たり前なのは省いてるっ

**Comment by rafale2k** [comment]
管理権限の追加とか剥奪とかも？

**Comment by aphmaunejitsu** [comment]
確かにっ
- 管理権限を追加する
- 管理権限を剥奪する

**Comment by aphmaunejitsu** [comment]
issueが減っては増えて(ﾉ∀`)

**Comment by rafale2k** [comment]
NG画像はめんどくさそう
大量にあるけどがんばって！
うちはクリーンインストールしてアップデートかけただけでDEこけたから
しばらくは力になれないｗ

**Comment by rafale2k** [comment]
\fuel\app\modules\nejitsu\classes\controller\nejitsu\
以下のファイルが読めない？

\fuel\app\modules\nejitsu\themes\nejitsu\
以下は構成中なのかな？
毎度お疲れ様でやんす

**Comment by aphmaunejitsu** [comment]
\fuel\app\modules\nejitsu\classes\controller\nejitsu ←まだディレクトリだけっ
\fuel\app\modules\nejitsu\themes\nejitsu ← 構成中ですっ

**Comment by aphmaunejitsu** [comment]
管理もレスポンシブだけど、スマホ系は考えない

**Comment by rafale2k** [comment]
スマホメインの俺涙目ｗｗｗ

**Comment by aphmaunejitsu** [comment]
一応、レスポンシブになってるから使えるっちゃ使えるよ！w

**Comment by rafale2k** [comment]
ｺｿｰﾘ
feature/44_admin
のブランチは消してもいいんじゃなかろうか

**Comment by aphmaunejitsu** [comment]
たしかにっ。ちょっと整理するなりよ

**Comment by rafale2k** [comment]
年度末の忙しい時期にごめんね

**Comment by rafale2k** [comment]
ﾋｿﾋｿ
