### ISSUE TITLE
サムネイル

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#5]
サムネイルもやるお！

- サムネオンオフ機能付き
- モザイク機能付き

**Comment by rafale2k** [comment]
よし、デフォで軽くモザイクも入れよう！(無茶
C#なら書けるけど、php は読むだけマンなので
いろいろ好き放題言うおｗ

**Comment by aphmaunejitsu** [comment]
大丈夫だ、問題ないw
※ただし鯖容量食う

**Comment by rafale2k** [comment]
容量は、単品のサイズ多めで
そこそこの数で流れるようにしたら良いかなと
つか前の管理人さん頑張りすぎ；；

**Comment by aphmaunejitsu** [comment]
モザイクはモザイク機能 -> #6
サムネオンオフは画像一覧 -> #4
