### ISSUE TITLE
Dockerに載せる

### ISSUE THREAD

**Issue by aphmaunejitsu** [aphmaunejitsu/uproda#61]

**Comment by rafale2k** [comment]
何それ楽しそう
だけど多分さくらあたりのVPSなんだろうなぁ
テストもしくはいずれ移行する際にいいんだろうけど

**Comment by aphmaunejitsu** [comment]
さくらのVPSも頑張ればDockerを導入できた予感・・・
パフォーマンス落ちるけどっ

**Comment by rafale2k** [comment]
でもお手軽よねぇ…
期待していいのかしら
