### ISSUE TITLE
荒らし対策

### ISSUE THREAD

**Issue by rafale2k** [aphmaunejitsu/uproda#9]
jp以外弾くとして、recaptchaとか
NGワードとかどこまでやりますかね？

**Comment by aphmaunejitsu** [comment]
TORの出口は、とりあえず拒否っちゃう
NGワードも、Imageboardから一旦引っ張ってきておく予定
recapchaは必須。爆撃はきついぃ

**Comment by rafale2k** [comment]
あー、今回Torも使われてたんでしたっけ
NGワードはあれは優秀
rechapchaのPHPの組み込みはわからんちんｗ

**Comment by aphmaunejitsu** [comment]
CAPTCHAは、これ利用予定どすー
[Auth_Kitten](https://github.com/ha1t/php-Auth_Kittenl)

**Comment by rafale2k** [comment]
リンク踏んだら404食らったおｗ

**Comment by aphmaunejitsu** [comment]
余分な1文字が入ってたっ
[Auth_Kitten](https://github.com/ha1t/php-Auth_Kitten)

**Comment by aphmaunejitsu** [comment]
アップロードのキャプチャ対応は → #16

**Comment by aphmaunejitsu** [comment]
TOR対策 → #17

**Comment by aphmaunejitsu** [comment]
#16, #17 一応終わった。新しくなんか思いついたら、新しくIssue作るっ
